theme: minima

title: Learn to create a github Page
author: Andrew Ott
description: > # this means to ignore newlines until "baseurl:"
  Learning to create a beautiful github page


show_excerpts: true # set to false to remove excerpts on the homepage
