title: Learning to use GitHub Pages
author: Andrew Ott
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing.


show_excerpts: true # set to false to remove excerpts on the homepage
